#ifndef AE_EFFECTVERS_H
#define AE_EFFECTVERS_H

#define AEFX_API_VERSION 8
#define AEFX_API_SUBVERS ' '
#define APFXp_CODE_VERSION 0
#define PF_PLUG_IN_VERSION 13
#define PF_PLUG_IN_SUBVERS 20

#endif
